[package]
name = "suipad"
version = "0.0.1"

[dependencies]
MoveStdlib = { local = "/Users/utpal/Desktop/projects/sui/sui/crates/sui-framework/packages/move-stdlib/" }
Sui = { local = "/Users/utpal/Desktop/projects/sui/sui/crates/sui-framework/packages/sui-framework" }


[addresses]
suipad =  "0x0"
